- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/content_idea.md
- .github/ISSUE_TEMPLATE/design_issue.md
- .github/ISSUE_TEMPLATE/docs_improvement.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/missing_feature.md
- CONTRIBUTING.md
A meta PR! This PR is attempting to establish standard practices and tools to streamline development.
> Process documentation and tools

- docs/src/rfc/001-customization-overhaul.md
- docs/src/rfc/active/001-customization-overhaul.md
Thoughts on a holistic overhaul of FoP's customization systems.
> RFC: Customization overhaul

- src/combat/attack.rs
- src/combat/conditions.rs
- src/combat/tiles.rs
- src/core/stats.rs
Fixes: https://github.com/Leafwing-Studios/fonts-of-power/issues/79
> Addressing clippy's concerns.

- docs/src/character-options/classes/alchemist/features.md
- docs/src/character-options/classes/bladesworn/features.md
- docs/src/character-options/classes/conduit/features.md
- docs/src/character-options/classes/incarnation/features.md
- docs/src/character-options/classes/paragon/features.md
- docs/src/character-options/classes/ritualist/features.md
- docs/src/character-options/classes/soulbinder/features.md
- docs/src/character-options/classes/touched/features.md
- docs/src/character-options/classes/trickster/features.md
- docs/src/character-options/classes/weaver/features.md
- docs/src/character-options/classes/wildshaper/features.md
Making progress towards: https://github.com/Leafwing-Studios/fonts-of-power/issues/88
Addresses: https://github.com/Leafwing-Studios/fonts-of-power/issues/90
> Reworking auto-generated markdowns for class features. 

- docs/src/rules/attributes.md
- docs/src/rules/building-blocks.md
- docs/src/rules/combat/attacking-and-defending.md
- docs/src/rules/resources-and-resting.md
> Prowess should affect max life, rather than basic defense

- docs/src/character-options/character-creation.md
- docs/src/rules/attributes.md
> Expertise affects skills known

- docs/src/character-options/classes/bladesworn/features.md
> Fix missing details for Bladesworn feature

- docs/src/character-options/gear/README.md
- docs/src/rules/narrative-mechanics/experience.md
> Make rules around equipped gear points even clearer

- docs/src/character-options/classes/ritualist/powers.md
- docs/src/rules/combat/conditions/ailments.md
- docs/src/rules/combat/elements.md
Fixes #95. Well, at least for now.
> Remove Unlucky ailment

- docs/src/character-options/classes/trickster/combat_feats.md
- docs/src/character-options/feats/defensive-feats.md
- docs/src/character-options/feats/monstrous-combat-feats.md
Removed Brawny and Scrawny duplicates from monster combat feats
> Small Typo

- docs/src/character-options/classes/alchemist/concoctions.md
Orca's Smash
Hermit's Shell
Dolphin's Play
> Markdown lints + adding in some concotion names for missing ones.

- rulebook/src/character-options/gear/README.md
- rulebook/src/rules/combat/acting-in-combat/actions.md
- rulebook/src/worldspeakers/trinkets.md
> Add trinket rules

- rulebook/src/rules/combat/round-turns-space.md
Fixes #72.
This strikes a good balance between interest, hidden information and ease of play. Requires props, but they're very simple.
> Card-based turn-order rules

- rulebook/src/character-options/classes/alchemist/combat_feats.md
- rulebook/src/character-options/classes/bladesworn/features.md
- rulebook/src/character-options/classes/devout/combat_feats.md
- rulebook/src/character-options/classes/incarnation/combat_feats.md
- rulebook/src/character-options/classes/paragon/combat_feats.md
- rulebook/src/character-options/classes/touched/combat_feats.md
- rulebook/src/character-options/feats/defensive-feats.md
> Add more Defend-centric combat feats

- rulebook/src/character-options/classes/alchemist/combat_feats.md
- rulebook/src/character-options/classes/alchemist/exploration_feats.md
- rulebook/src/character-options/classes/alchemist/features.md
- rulebook/src/character-options/classes/conduit/combat_feats.md
- rulebook/src/character-options/feats/exploration-feats.md
- rulebook/src/hacking/class_template/features.md
I made some changes, but also left comments with questions/concerns
> Design review: alchemist

- rulebook/src/rules/combat/acting-in-combat/actions.md
> Remove Jostle

- rulebook/src/character-options/classes/touched/combat_feats.md
- rulebook/src/character-options/classes/touched/exploration_feats.md
- rulebook/src/character-options/classes/touched/features.md
- rulebook/src/character-options/feats/exploration-feats.md
> Touched class review

- rulebook/src/character-options/classes/bladesworn/features.md
> Add Martial Artist subclass

- rulebook/src/character-options/classes/lifespeaker/features.md
Questions for reviewer:
- Is the intended play pattern of the Horde capstone clear?
- Is the power level of the Absolute Unit capstone appropriate?
- Is the fantasy / feel of the Absolute Unit and Horde capstone compelling?
> Make Lifebreather capstone more interesting

- rulebook/src/character-options/classes/alchemist/features.md
- rulebook/src/character-options/classes/alchemist/powers.md
> Add alchemist powers

- rulebook/src/character-options/classes/_experimental/wildshaper/powers.md
- rulebook/src/character-options/classes/alchemist/powers.md
- rulebook/src/character-options/classes/bladesworn/powers.md
- rulebook/src/character-options/classes/conduit/powers.md
- rulebook/src/character-options/classes/devout/powers.md
- rulebook/src/character-options/classes/elementalist/combat_feats.md
- rulebook/src/character-options/classes/elementalist/exploration_feats.md
- rulebook/src/character-options/classes/elementalist/features.md
- rulebook/src/character-options/classes/elementalist/powers.md
- rulebook/src/character-options/classes/paragon/powers.md
- rulebook/src/character-options/classes/soulbinder/features.md
- rulebook/src/character-options/classes/soulbinder/powers.md
- rulebook/src/character-options/classes/trickster/powers.md
- rulebook/src/character-options/classes/weaver/powers.md
- rulebook/src/character-options/gear/README.md
- rulebook/src/hacking/class_template/powers.md
> Add elementalist powers

- rulebook/src/character-options/classes/alchemist/exploration_feats.md
- rulebook/src/character-options/classes/alchemist/features.md
- rulebook/src/character-options/gear/README.md
- rulebook/src/character-options/gear/consumables/base_effects.md
- rulebook/src/character-options/gear/consumables/modifiers.md
- rulebook/src/rules/downtime-activities.md
- rulebook/src/worldspeakers/affixes.md
> Consumables rework

- rulebook/src/character-options/classes/_experimental/wildshaper/exploration_feats.md
- rulebook/src/character-options/classes/paragon/exploration_feats.md
- rulebook/src/character-options/classes/paragon/features.md
- rulebook/src/character-options/feats/monstrous-combat-feats.md
- rulebook/src/character-options/feats/monstrous-exploration-feats.md
- rulebook/src/character-options/species/_splat/sylvan/exploration_feats.md
- rulebook/src/character-options/species/_splat/sylvan/sylvan.md
- rulebook/src/character-options/species/automaton/exploration_feats.md
- rulebook/src/character-options/species/crystalline/exploration_feats.md
- rulebook/src/character-options/species/fae/exploration_feats.md
- rulebook/src/character-options/species/human/exploration_feats.md
- rulebook/src/character-options/species/slime/exploration_feats.md
- rulebook/src/rules/downtime-activities.md
- rulebook/src/rules/skills/README.md
Fixes #205. Good splat material (with the Wildshaper!), but way too high complexity for base right now.
> Cut the Shape downtime activity

- rulebook/src/character-options/classes/trickster/combat_feats.md
- rulebook/src/character-options/classes/trickster/exploration_feats.md
- rulebook/src/character-options/classes/trickster/features.md
- rulebook/src/character-options/classes/trickster/powers.md
> Polish and design pass for trickster
